config/routes.rb
Eightround::Application.routes.draw do
  resources :extensions
  resources :customers
  resources :ivrs

  get "home/index"

  root :to => 'home#index'

end

app/models/customer.rb
class Customer < ActiveRecord::Base
  paginates_per 10

  has_many :ivrs,
           :foreign_key => :customer_id,
           :dependent => :delete_all

#  has_many :extensions,
#           :foreign_key => :customer_id,
#           :dependent => :delete_all
end

app/models/extension.rb
class Extension < ActiveRecord::Base
end

app/models/ivr.rb
class Ivr < ActiveRecord::Base
  def Ivr.create_menu(customer_id)
    for i in 1..9
      ivr = Ivr.new
      ivr.customer_id = customer_id
      ivr.level = i
      ivr.save
    end
  end
end

app/models/ivr_member.rb
class IvrMember < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.page(params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @customers }
    end
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
    @customer = Customer.find(params[:id])
    @menu = Ivr.find_all_by_customer_id(@customer.id)
    @extensions = Extension.find_all_by_customer_id(@customer.id)
    if @menu.empty?
      Ivr.create_menu(@customer.id)
    end
    @menu = Ivr.find_all_by_customer_id(@customer.id)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @customer }
    end
  end

  # GET /customers/new
  # GET /customers/new.json
  def new
    @customer = Customer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @customer }
    end
  end

  # GET /customers/1/edit
  def edit
    @customer = Customer.find(params[:id])
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(params[:customer])

    respond_to do |format|
      if @customer.save
        Ivr.create_menu(@customer.id)
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render json: @customer, status: :created, location: @customer }
      else
        format.html { render action: "new" }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /customers/1
  # PUT /customers/1.json
  def update
    @customer = Customer.find(params[:id])

    respond_to do |format|
      if @customer.update_attributes(params[:customer])
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer = Customer.find(params[:id])
    @customer.destroy

    respond_to do |format|
      format.html { redirect_to customers_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/extensions_controller.rb
class ExtensionsController < ApplicationController
  def create
    ext = Extension.find_by_extension(params[:extension][:extension])
    if ext == nil
      ext = Extension.new(params[:extension])
    else
      ext.name = params[:extension][:name]
    end
    ext.save
    redirect_to :controller => "customers", :action => "show", :id => params[:extension][:customer_id]
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @ext = Extension.find(params[:id])
    @ext.destroy

    redirect_to :controller => "customers", :action => "show", :id => @ext.customer_id
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/ivrs_controller.rb
class IvrsController < ApplicationController
  # PUT /ivrs/1
  # PUT /ivrs/1.json
  def create
    ivr = Ivr.find_by_customer_id_and_level(params[:ivr][:customer_id], params[:ivr][:level])
    ivr.description = params[:ivr][:description]
    ivr.call_type = params[:ivr][:call_type]
    ivr.save

    redirect_to :controller => "customers", :action => "show", :id => params[:ivr][:customer_id]
#    @ivr = Customer.find(params[:id])
#
#    respond_to do |format|
#      if @customer.update_attributes(params[:ivr_group])
#        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
#        format.json { head :no_content }
#      else
#        format.html { render action: "edit" }
#        format.json { render json: @customer.errors, status: :unprocessable_entity }
#      end
#    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/customers/_form.html.haml
.group
  = f.label :name, t("activerecord.attributes.customer.name", :default => "Name"), :class => :label
  = f.text_field :name, :class => 'text_field'
  %span.description Ex: a simple text
.group
  = f.label :email, t("activerecord.attributes.customer.email", :default => "Email"), :class => :label
  = f.text_field :email, :class => 'text_field'
  %span.description Ex: a simple text
.group
  = f.label :server_id, t("activerecord.attributes.customer.server_id", :default => "Server"), :class => :label
  = f.number_field :server_id, :class => 'number_field'
  %span.description Ex: a simple text
.group
  = f.label :lync_server, t("activerecord.attributes.customer.lync_server", :default => "Lync server"), :class => :label
  = f.text_field :lync_server, :class => 'text_field'
  %span.description Ex: a simple text
.group
  = f.label :sip_trunk, t("activerecord.attributes.customer.sip_trunk", :default => "Sip trunk"), :class => :label
  = f.text_field :sip_trunk, :class => 'text_field'
  %span.description Ex: a simple text
.group
  = f.label :office_hour, t("activerecord.attributes.customer.office_hour", :default => "Office hour"), :class => :label
  = f.text_field :office_hour, :class => 'text_field'
  %span.description Ex: a simple text
.group.navform.wat-cf
  %button.button{:type => "submit"}
    = image_tag("web-app-theme/icons/tick.png", :alt => "#{t("web-app-theme.save", :default => "Save")}")
    = t("web-app-theme.save", :default => "Save")
  %span.text_button_padding= t("web-app-theme.or", :default => "or")
  = link_to t("web-app-theme.cancel", :default => "Cancel"), customers_path, :class => "text_button_padding link_button"

app/views/customers/_sidebar.html.haml
.block
  %h3 IVR Group
  .content
    %h2
    .inner
      = form_for :ivr, :url => ivrs_path, :html => { :class => :form } do |f|
        .group
          = f.label :description, t("activerecord.attributes.ivr.description", :default => "Description"), :class => :label
          = f.text_field :description, :class => 'text_field'
        .group
          = f.label :call_type, t("activerecord.attributes.ivr.call_type", :default => "Type"), :class => :label
          = select_tag "ivr[call_type]", options_for_select(['NONE', 'RING GROUP', 'HUNT GROUP'])
        .group
          %table{:style => "width: 100%"}
            %tr
              %td{:style => "width: 40%"}
                = f.label :member, t("activerecord.attributes.ivr.member", :default => "Member"), :class => :label
              %td{:style => "width: 10%"}
              %td{:style => "width: 10%"}
                = hidden_field :ivr, :level, :value => ""
                = hidden_field :ivr, :customer_id, :value => @customer.id
              %td
                = f.label :avail, t("activerecord.attributes.ivr.avail", :default => "Avail"), :class => :label
            %tr
              :javascript
                function move_item(from, to) {
                  var from_options = document.getElementById(from).options;
                  var to = document.getElementById(to);
                  var i;
                  for (i=0;i<from_options.length; i++) {
                    if (from_options.item(i).selected == true && from_options.item(i).text != "NONE") {
                      if (to.item(0).text == "NONE")
                        to.remove(0);
                      from_options.item(i).selected = false;

                      to.add(from_options.item(i));
                    }
                  }
                  if (from_options.length == 0) {
                    var option = document.createElement("option");
                    option.text = "NONE";
                    from_options.add(option);
                  }
                }
                function load_member() {
                  var mem_options = document.getElementById("ivr_member").options;
                  var i;
                  for (i=0;i<mem_options.length; i++) {
                    if (mem_options.item(i).value != "NONE")
                      mem_options.item(i).selected = true;
                  }
                  
                  var avail = document.getElementById("ivr_avail");
                  avail.remove();
                }
                function load_form(l, desc, ctype) {
                  document.getElementById("ivr_level").value = l;
                  document.getElementById("ivr_description").value = desc;
                  document.getElementById("ivr_call_type").value = ctype;
                }
              %td
                = select_tag "ivr[member]", options_for_select(["NONE"]), :size => 4, :multiple => true
              %td{:style => "veritical-align: bottom"}
                %button.button{:type => "button", :onclick => 'move_item("ivr_avail", "ivr_member")'}
                  = t("web-app-theme.add", :default => "<-")
                &nbsp;
                %button.button{:type => "button", :onclick => 'move_item("ivr_member", "ivr_avail")'}
                  = t("web-app-theme.add", :default => "->")
              %td
              %td
                - if @extensions.empty?
                  = select_tag "ivr[avail]", options_for_select(["NONE"]), :size => 4
                - else
                  - exts = @extensions.map {|c| c.extension}.flatten.uniq.sort
                  = select_tag "ivr[avail]", options_for_select(exts), :size => 4
        .group.navform.wat-cf
          %button.button{:type => "submit", :onclick => 'load_member()'}
            = image_tag("web-app-theme/icons/tick.png", :alt => "#{t("web-app-theme.save", :default => "Add")}")
            = t("web-app-theme.save", :default => "OK")

app/views/customers/edit.html.haml
.block
  .secondary-navigation
    %ul.wat-cf
      %li.first= link_to "#{t("web-app-theme.list", :default => "List")}", customers_path
      %li= link_to "#{t("web-app-theme.new", :default => "New")}", new_customer_path
      %li.active= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_customer_path
  .content
    %h2.title
      = t("web-app-theme.edit", :default => "Edit")
      Customer
    .inner
      = form_for @customer, :url => customer_path(@customer), :html => { :class => :form } do |f|
        = render :partial => "form", :locals => {:f => f}

app/views/customers/index.html.haml
.block
  .secondary-navigation
    %ul.wat-cf
      %li.first.active= link_to "#{t("web-app-theme.list", :default => "List")}", customers_path
      %li= link_to "#{t("web-app-theme.new", :default => "New")}", new_customer_path
  .content
    %h2.title
      = t("web-app-theme.all", :default => "All")
      Customers
    .inner
      %table.table
        %tr
          %th.first ID
          %th
            = t("activerecord.attributes.customer.name", :default => t("activerecord.labels.name", :default => "Name"))
          %th= t("web-app-theme.created_at", :default => "Created at")
          %th.last &nbsp;
        - @customers.each do |customer|
          %tr{:class => cycle("odd", "even")}
            %td
              = customer.id
            %td
              = link_to customer.name, customer_path(customer)
            %td
              = customer.created_at
            %td.last
              = link_to "#{t("web-app-theme.delete", :default => "Delete")}", customer_path(customer), :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}"
      .actions-bar.wat-cf
        .actions
        = paginate @customers

app/views/customers/new.html.haml
.block
  .secondary-navigation
    %ul.wat-cf
      %li.first= link_to "#{t("web-app-theme.list", :default => "List")}", customers_path
      %li.active= link_to "#{t("web-app-theme.new", :default => "New")}", new_customer_path
  .content
    %h2.title
      = t("web-app-theme.new", :default => "New")
      Customer
    .inner
      = form_for :customer, :url => customers_path, :html => { :class => :form } do |f|
        = render :partial => "form", :locals => {:f => f}

app/views/customers/show.html.haml
.block
  .secondary-navigation
    %ul.wat-cf
      %li.first= link_to "#{t("web-app-theme.list", :default => "List")}", customers_path
      %li= link_to "#{t("web-app-theme.new", :default => "New")}", new_customer_path
      %li.active= link_to "#{t("web-app-theme.show", :default => "Show")}", customer_path
  .content
    .inner
      %table{:style => "width: 100%"}
        %tr
          %td
            %h2
              = @customer.name
          %td
            %b
              = t("activerecord.attributes.customer.email", :default => t("activerecord.labels.email", :default => "Email"))
              \:
            = @customer.email
        %tr
          %td
            %b
              = t("activerecord.attributes.customer.server_id", :default => t("activerecord.labels.server_id", :default => "Server"))
              \:
            = @customer.server_id
          %td
            %b
              = t("activerecord.attributes.customer.office_hour", :default => t("activerecord.labels.office_hour", :default => "Office hour"))
              \:
            = @customer.office_hour
        %tr
          %td
            %b
              = t("activerecord.attributes.customer.lync_server", :default => t("activerecord.labels.lync_server", :default => "Lync server"))
              \:
            = @customer.lync_server
          %td
            %b
              = t("activerecord.attributes.customer.sip_trunk", :default => t("activerecord.labels.sip_trunk", :default => "Sip trunk"))
              \:
            = @customer.sip_trunk
      %br
      .wat-cf
        = link_to image_tag("web-app-theme/icons/application_edit.png", :alt => "#{t("web-app-theme.edit", :default=> "Edit")}") + " " + t("web-app-theme.edit", :default=> "Edit"), edit_customer_path(@customer), :class => "button"
        = link_to image_tag("web-app-theme/icons/cross.png", :alt => "#{t("web-app-theme.delete", :default=> "Delete")}") + " " + t("web-app-theme.delete", :default => "Delete"), customer_path(@customer), :method => "delete", :class => "button", :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}"
      %br
      %hr
      %br
      %h2 Extensions 
      :javascript
        function edit_extension(name, ext) {
          document.getElementById('extension_name').value = name;
          document.getElementById('extension_extension').value = ext;
        }
      = form_for :extension, :url => extensions_path, :html => { :class => :form } do |f|
        %table
          %tr{:style => "vertical-align: bottom;"}
            %td
              = f.label :extension, t("activerecord.attributes.extension.extension", :default => "Extension"), :class => :label
              = f.text_field :extension, :class => 'text_field', :size => 10
            %td &nbsp;&nbsp;&nbsp;&nbsp;
            %td
              = f.label :name, t("activerecord.attributes.extension.name", :default => "Name"), :class => :label
              = f.text_field :name, :class => 'text_field', :size => 30
            %td &nbsp;&nbsp;&nbsp;&nbsp;
            %td
              = hidden_field :extension, :customer_id, :value => @customer.id
              %button.button{:type => "submit"}
                = image_tag("web-app-theme/icons/tick.png", :alt => "#{t("web-app-theme.save", :default => "Add")}")
                = t("web-app-theme.save", :default => "Add")
      %br
      %table.table
        %tr
          %th.first
          %th Extension
          %th Name
          %th.last &nbsp
        - @extensions.each do |ext|
          %tr{:class => cycle("odd", "even")}
            %td
            %td
              = ext.extension
            %td
              = ext.name
            %td.last
              = link_to 'Edit', '#', :onclick => "edit_extension('#{ext.name}', '#{ext.extension}')"
              |
              = link_to "#{t("web-app-theme.delete", :default => "Remove")}", extension_path(ext), :method => :delete
      %br
      %h2 IVR Groups
      %table.table
        %tr
          %th.first #
          %th Description
          %th Type
          %th Members
          %th.last &nbsp
        - @menu.each do |item|
          %tr{:class => cycle("odd", "even")}
            %td
              = link_to item.level, "#", :onclick => "load_form(#{item.level}, '#{item.description}', '#{item.call_type}')"
            %td
              = item.description
            %td
              = item.call_type
            %td
              John Doe, Joe Blow, Alex Smart, Bill Gates, George
            %td.last
              Upload voice | Change | Clear
- content_for :sidebar, render(:partial => 'sidebar')

app/views/home/_sidebar.html.haml
.block.notice
  %h3 Simple Block
  .content
    %p Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
.block
  %h3 Links
  %ul.navigation
    %li
      %a{:href => "#"} Link 1
    %li
      %a{:href => "#"} Link 2

app/views/home/index.html.haml
#block-text.block
  .content
    %h2.title Home
    .inner
      %p.first
        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
        = succeed "," do
          %span.hightlight Excepteur sint occaecat cupidatat non proident
        sunt in culpa qui officia deserunt mollit anim id est laborum.
      %p
        %span.small Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore
      %p
        %span.gray Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore
      %hr/
      %p
        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
        = succeed "," do
          %span.hightlight Excepteur sint occaecat cupidatat non proident
        sunt in culpa qui officia deserunt mollit anim id est laborum.
- content_for :sidebar, render(:partial => 'sidebar')

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title UC-ACD
    = stylesheet_link_tag 'web_app_theme'
    = javascript_include_tag 'application'
    = csrf_meta_tag
  %body
    #container
      #header
        %h1
          %a{:href => "/"} UC-ACD
        #user-navigation
          %ul.wat-cf
            %li
              %a{:href => "#"}= t("web-app-theme.profile", :default => "Profile")
            %li
              %a{:href => "#"}= t("web-app-theme.settings", :default => "Settings")
            %li
              %a.logout{:href => "/logout"}= t("web-app-theme.logout", :default => "Logout")
        #main-navigation
          %ul.wat-cf
            %li{:class => (params[:controller] == "home" ? "first active" : "first")}
              = link_to "Home", root_path
            %li{:class => (params[:controller] == "customers" ? "active" : nil)}
              = link_to "Customers", customers_path
      #wrapper.wat-cf
        .flash
          - flash.each do |type, message|
            %div{:class => "message #{type}"}
              %p= message
        #main
          = yield
          #footer
            .block
              %p
                Copyright &copy; #{Time.now.year} UC-ACD.
        #sidebar
          = yield :sidebar